//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulloa.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int id_registro { get; set; }
        public int fk_persona { get; set; }
        public int fk_rol { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
